# Generated by Django 5.2.12 on 2026-03-09 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_currency_exchangerate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={"verbose_name": "Devise", "verbose_name_plural": "Devises"},
        ),
        migrations.AlterModelOptions(
            name="exchangerate",
            options={
                "verbose_name": "Taux de change",
                "verbose_name_plural": "Taux de change",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Pourcentage des frais générés reversé à l'agent",
                max_digits=5,
                verbose_name="Taux de commission (%)",
            ),
        ),
        migrations.AlterField(
            model_name="currency",
            name="code",
            field=models.CharField(
                max_length=3, unique=True, verbose_name="Code (e.g. USD)"
            ),
        ),
        migrations.AlterField(
            model_name="currency",
            name="is_reference",
            field=models.BooleanField(
                default=False, verbose_name="Devise de référence"
            ),
        ),
        migrations.AlterField(
            model_name="currency",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="currency",
            name="symbol",
            field=models.CharField(blank=True, max_length=10, verbose_name="Symbole"),
        ),
        migrations.AlterField(
            model_name="exchangerate",
            name="base_currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="base_rates",
                to="core.currency",
                verbose_name="Devise source",
            ),
        ),
        migrations.AlterField(
            model_name="exchangerate",
            name="date_updated",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Dernière mise à jour"
            ),
        ),
        migrations.AlterField(
            model_name="exchangerate",
            name="rate",
            field=models.DecimalField(
                decimal_places=10, max_digits=20, verbose_name="Taux"
            ),
        ),
        migrations.AlterField(
            model_name="exchangerate",
            name="target_currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_rates",
                to="core.currency",
                verbose_name="Devise cible",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Téléphone"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrateur"),
                    ("AGENT", "Agent"),
                    ("ASSOCIATE", "Associé"),
                    ("INVESTOR", "Investisseur"),
                ],
                default="ADMIN",
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
    ]
