# Generated by Django 5.2.12 on 2026-03-10 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_currency_options_alter_exchangerate_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Création"),
                            ("UPDATE", "Modification"),
                            ("DELETE", "Suppression"),
                            ("LOGIN", "Connexion"),
                            ("LOGOUT", "Déconnexion"),
                            ("LOGIN_FAILED", "Échec connexion"),
                            ("TRANSACTION", "Transaction"),
                            ("EXPENSE", "Dépense"),
                            ("FEE_GRID", "Grille de frais"),
                            ("CURRENCY", "Devise"),
                            ("EXCHANGE_RATE", "Taux de change"),
                        ],
                        max_length=20,
                        verbose_name="Action",
                    ),
                ),
                ("model_name", models.CharField(max_length=100, verbose_name="Modèle")),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="ID de l'objet",
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Représentation de l'objet",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Modifications"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adresse IP"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date/Heure"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal d'audit",
                "verbose_name_plural": "Journaux d'audit",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="core_auditl_user_id_2a1528_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="core_auditl_action_f07419_idx",
                    ),
                    models.Index(
                        fields=["model_name", "-timestamp"],
                        name="core_auditl_model_n_9470ca_idx",
                    ),
                ],
            },
        ),
    ]
