# Generated by Django 5.0.10 on 2026-03-10 16:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_user_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="Mois",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Année")),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("end_date", models.DateField(verbose_name="Date de fin")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Ouvert"),
                            ("CLOSED", "Clôturé"),
                            ("PAID", "Payé"),
                        ],
                        default="OPEN",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "reserve_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=10.0,
                        help_text="Pourcentage des revenus mis en réserve avant calcul des bénéfices",
                        max_digits=5,
                        verbose_name="Pourcentage de réserve (%)",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True,
                        help_text="Date à laquelle les salaires seront payés",
                        null=True,
                        verbose_name="Date de paie prévue",
                    ),
                ),
                (
                    "total_fees",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Total des frais",
                    ),
                ),
                (
                    "total_expenses",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Total des dépenses",
                    ),
                ),
                (
                    "reserve_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Montant réservé",
                    ),
                ),
                (
                    "net_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Bénéfice net",
                    ),
                ),
                (
                    "total_salaries",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Total des salaires",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "Période de paie",
                "verbose_name_plural": "Périodes de paie",
                "ordering": ["-year", "-month"],
                "unique_together": {("month", "year")},
            },
        ),
        migrations.CreateModel(
            name="MonthlySalary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pourcentage des bénéfices alloué à cet agent",
                        max_digits=5,
                        verbose_name="Pourcentage de commission (%)",
                    ),
                ),
                (
                    "base_salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Calculé automatiquement: Bénéfices × Pourcentage",
                        max_digits=20,
                        verbose_name="Salaire de base",
                    ),
                ),
                (
                    "bonus_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Bonus manuel défini par l'administrateur",
                        max_digits=20,
                        verbose_name="Bonus",
                    ),
                ),
                (
                    "total_salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Salaire de base + Bonus",
                        max_digits=20,
                        verbose_name="Salaire total",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Montant payé",
                    ),
                ),
                (
                    "paid_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de paiement"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("PAID", "Payé"),
                            ("PARTIAL", "Partiellement payé"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "payment_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes sur le paiement (ex: payé en espèces)",
                        verbose_name="Notes de paiement",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Créé le"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        limit_choices_to={"role": "AGENT"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Agent",
                    ),
                ),
                (
                    "pay_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_salaries",
                        to="core.payperiod",
                        verbose_name="Période de paie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Salaire mensuel",
                "verbose_name_plural": "Salaires mensuels",
                "ordering": [
                    "-pay_period__year",
                    "-pay_period__month",
                    "agent__username",
                ],
                "unique_together": {("pay_period", "agent")},
            },
        ),
    ]
