# Generated by Django 5.2.12 on 2026-03-09 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_currency_options_alter_exchangerate_options_and_more"),
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expense",
            options={"verbose_name": "Dépense", "verbose_name_plural": "Dépenses"},
        ),
        migrations.AlterModelOptions(
            name="partnercontract",
            options={
                "verbose_name": "Contrat Partenaire",
                "verbose_name_plural": "Contrats Partenaires",
            },
        ),
        migrations.AlterModelOptions(
            name="partnerpayment",
            options={
                "verbose_name": "Paiement Partenaire",
                "verbose_name_plural": "Paiements Partenaires",
            },
        ),
        migrations.AlterField(
            model_name="expense",
            name="admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Administrateur",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, verbose_name="Montant"
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Catégorie"
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Commentaire"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.currency",
                verbose_name="Devise",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(auto_now_add=True, verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="expense",
            name="destination",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Destination"
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="reason",
            field=models.CharField(max_length=255, verbose_name="Motif"),
        ),
        migrations.AlterField(
            model_name="partnercontract",
            name="amount_engaged",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, verbose_name="Montant engagé"
            ),
        ),
        migrations.AlterField(
            model_name="partnercontract",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.currency",
                verbose_name="Devise",
            ),
        ),
        migrations.AlterField(
            model_name="partnercontract",
            name="duration_months",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Durée (mois)"
            ),
        ),
        migrations.AlterField(
            model_name="partnercontract",
            name="expected_return_percent",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Retour attendu (%)"
            ),
        ),
        migrations.AlterField(
            model_name="partnercontract",
            name="partner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Partenaire",
            ),
        ),
        migrations.AlterField(
            model_name="partnercontract",
            name="start_date",
            field=models.DateField(verbose_name="Date de début"),
        ),
        migrations.AlterField(
            model_name="partnercontract",
            name="status",
            field=models.CharField(
                default="ACTIVE", max_length=20, verbose_name="Statut"
            ),
        ),
        migrations.AlterField(
            model_name="partnercontract",
            name="type",
            field=models.CharField(
                choices=[("ASSOCIATE", "Associé"), ("INVESTOR", "Investisseur")],
                max_length=20,
                verbose_name="Type de contrat",
            ),
        ),
        migrations.AlterField(
            model_name="partnerpayment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, verbose_name="Montant payé"
            ),
        ),
        migrations.AlterField(
            model_name="partnerpayment",
            name="contract",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="finance.partnercontract",
                verbose_name="Contrat lié",
            ),
        ),
        migrations.AlterField(
            model_name="partnerpayment",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.currency",
                verbose_name="Devise",
            ),
        ),
        migrations.AlterField(
            model_name="partnerpayment",
            name="date",
            field=models.DateField(auto_now_add=True, verbose_name="Date de paiement"),
        ),
        migrations.AlterField(
            model_name="partnerpayment",
            name="note",
            field=models.TextField(blank=True, verbose_name="Note"),
        ),
    ]
