# Generated by Django 5.2.12 on 2026-03-09 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0002_currency_exchangerate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Caisse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "agent",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="caisse",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.currency"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeeGrid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("max_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("fee_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.currency"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Operation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_number", models.CharField(max_length=50, unique=True)),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("TRANSFER", "Transfert"), ("WITHDRAWAL", "Retrait")],
                        max_length=20,
                    ),
                ),
                ("amount_orig", models.DecimalField(decimal_places=2, max_digits=20)),
                ("amount_ref", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "exchange_rate",
                    models.DecimalField(decimal_places=10, max_digits=20),
                ),
                (
                    "fee_calculated",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("observation", models.TextField(blank=True, null=True)),
                ("status", models.CharField(default="COMPLETED", max_length=20)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "caisse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="operations.caisse",
                    ),
                ),
                (
                    "currency_orig",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations_orig",
                        to="core.currency",
                    ),
                ),
                (
                    "currency_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operations_ref",
                        to="core.currency",
                    ),
                ),
            ],
        ),
    ]
