# Generated by Django 5.2.12 on 2026-03-09 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_currency_options_alter_exchangerate_options_and_more"),
        ("operations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="caisse",
            options={"verbose_name": "Caisse", "verbose_name_plural": "Caisses"},
        ),
        migrations.AlterModelOptions(
            name="feegrid",
            options={
                "verbose_name": "Grille de Frais",
                "verbose_name_plural": "Grilles de Frais",
            },
        ),
        migrations.AlterModelOptions(
            name="operation",
            options={"verbose_name": "Opération", "verbose_name_plural": "Opérations"},
        ),
        migrations.AlterField(
            model_name="caisse",
            name="agent",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="caisse",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Agent titulaire",
            ),
        ),
        migrations.AlterField(
            model_name="caisse",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=20, verbose_name="Solde actuel"
            ),
        ),
        migrations.AlterField(
            model_name="caisse",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.currency",
                verbose_name="Devise de la caisse",
            ),
        ),
        migrations.AlterField(
            model_name="caisse",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nom de la caisse"),
        ),
        migrations.AlterField(
            model_name="feegrid",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.currency",
                verbose_name="Devise",
            ),
        ),
        migrations.AlterField(
            model_name="feegrid",
            name="fee_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, verbose_name="Frais Fixe"
            ),
        ),
        migrations.AlterField(
            model_name="feegrid",
            name="max_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, verbose_name="Montant Max"
            ),
        ),
        migrations.AlterField(
            model_name="feegrid",
            name="min_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, verbose_name="Montant Min"
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Agent responsable",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="amount_orig",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, verbose_name="Montant saisi"
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="amount_ref",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, verbose_name="Montant (REF USD)"
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="caisse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="operations.caisse",
                verbose_name="Caisse utilisée",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="currency_orig",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operations_orig",
                to="core.currency",
                verbose_name="Devise d'origine",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="currency_ref",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operations_ref",
                to="core.currency",
                verbose_name="Devise de référence",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="date_time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date & Heure"),
        ),
        migrations.AlterField(
            model_name="operation",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=10, max_digits=20, verbose_name="Taux utilisé"
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="fee_calculated",
            field=models.DecimalField(
                decimal_places=2, max_digits=20, verbose_name="Frais appliqués"
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="observation",
            field=models.TextField(blank=True, null=True, verbose_name="Commentaire"),
        ),
        migrations.AlterField(
            model_name="operation",
            name="status",
            field=models.CharField(
                default="COMPLETED", max_length=20, verbose_name="Statut"
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="transaction_number",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="N° Transaction"
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="type",
            field=models.CharField(
                choices=[("TRANSFER", "Transfert"), ("WITHDRAWAL", "Retrait")],
                max_length=20,
                verbose_name="Type d'opération",
            ),
        ),
    ]
