# Generated by Django 5.2.12 on 2026-03-10 12:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_auditlog"),
        ("operations", "0002_alter_caisse_options_alter_feegrid_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="caisse",
            index=models.Index(fields=["agent"], name="operations__agent_i_9eb1d4_idx"),
        ),
        migrations.AddIndex(
            model_name="caisse",
            index=models.Index(
                fields=["currency"], name="operations__currenc_4ac4d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="operation",
            index=models.Index(
                fields=["agent", "-date_time"], name="operations__agent_i_23c916_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="operation",
            index=models.Index(
                fields=["transaction_number"], name="operations__transac_ea0dc7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="operation",
            index=models.Index(fields=["status"], name="operations__status_ad168c_idx"),
        ),
        migrations.AddIndex(
            model_name="operation",
            index=models.Index(
                fields=["date_time"], name="operations__date_ti_6b7fcb_idx"
            ),
        ),
    ]
